version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
    timezone: "America/New_York"
  commit-message:
    prefix: "chore/gomod"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
    timezone: "America/New_York"
  commit-message:
    prefix: "chore/github-actions"


- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
    timezone: "America/New_York"
  commit-message:
    prefix: "chore/docker"