name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop
  paths_ignore:
    - README.md
    - 'docs/**'
    - '*.md'
  tags-ignore:
    - 'staging/**'
    - 'production/**'

env:
  ENV: test
  GITHUB_USER: ${{ github.actor }}
  GO_VERSION: '1.23.4'
  POSTGRES_VERSION: '15'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    container: golang:1.23.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Install dependencies
        run: make deps

      - name: Run linter
        run: GOFLAGS=-buildvcs=false make lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: golang:1.23.4
    services:
      zeus-postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: zeus-test-db
          POSTGRES_USER: admin_test
          POSTGRES_PASSWORD: admin_test
          PGPORT: 5441
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5441:5441

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: make deps

      - name: Run migrations
        run: make db-migrate

      - name: Run tests
        run: make test_ci

     